server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://olms-frontend:80;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://olms-backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
